/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Hello */

#ifndef _Included_jni_Hello
#define _Included_jni_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Hello
 * Method:    fromJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_Hello_fromJniString(JNIEnv *, jobject);

/*
 * Class:     jni_Hello
 * Method:    fromJniInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jni_Hello_fromJniInt(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
